!!python/object:simulation.Simulation
averageVehicleLength: 7.0
averageVehicleWidth: 2.5
duration: 50.0
interactionDistance: 25
minimumTimeHeadway: 2.0
timeStep: 0.1
vehicleLengthSD: 2.0
vehicleWidthSD: 0.75
seed: 45