!!python/object:simulation.Simulation
duration: 200
minNCompletedUsers: 130
timeStep: 0.1
safetyDistance: 1.0
verbose: False
seed: 32
increment: 4
rep: 15
dbName: stop-data.db
computeInteractions: True
