!!python/object:simulation.Simulation
duration: 1000
timeStep: 0.1
safetyDistance: 1.0
verbose: True
seed: 32
increment: 4
rep: 76
dbName: world.db
computeInteractions: True
minimumCompletedUsers : 70