!!python/object:simulation.Simulation
duration: 600
minNCompletedUsers: 200
timeStep: 0.1
safetyDistance: 1.0
verbose: True
seed: 44
increment: 4
rep: 30
dbName: sensitivity-analysis-data.db
computeInteractions: True
