!!python/object:simulation.Simulation
duration: 1000
timeStep: 0.1
safetyDistance: 1.0
verbose: False
seed: 32
increment: 4
rep: 40
dbName: world.db
computeInteractions: False
minimumCompletedUsers : 150