!!python/object:objectsofworld.World
speedLimit: 14
speedVariations: 5
alignments:
- !!python/object:objectsofworld.Alignment
  connected_alignment_idx: 1.0
  controlDevice: null
  crossingPoint: !!python/object:trafficintelligence.moving.Point
    x: 0.0
    y: 0.0
  distance_to_crossing_point: 1000.0
  idx: 0.0
  name: 'horizontal.yml'
  points: !!python/object:trafficintelligence.moving.Trajectory
    cumulativeDistances:
    - 0.0
    - 1000.0
    - 2000.0
    distances:
    - 1000.0
    - 1000.0
    positions:
    - - -1000.0
      - 0.0
      - 1000.0
    - - 0.0
      - 0.0
      - 0.0
  width: null
- !!python/object:objectsofworld.Alignment
  connected_alignment_idx: 0.0
  controlDevice: null
  crossingPoint: !!python/object:trafficintelligence.moving.Point
    x: 0.0
    y: 0.0
  distance_to_crossing_point: 1000.0
  idx: 1.0
  name: 'vertical.yml'
  points: !!python/object:trafficintelligence.moving.Trajectory
    cumulativeDistances:
    - 0.0
    - 1000.0
    - 2000.0
    distances:
    - 1000.0
    - 1000.0
    positions:
    - - 0.0
      - 0.0
      - 0.0
    - - -1000.0
      - 0.0
      - 1000.0
  width: null
controlDevices: null
crossingPoint: !!python/object:trafficintelligence.moving.Point
    x: 0.0
    y: 0.0
pedestrians: null
vehicleInputs:
- !!python/object:cars.VehicleInput
  alignmentIdx: 0.0
  desiredSpeedParameters:
  - 14.0
  - 2.0
  headwayDistributionParameters: null
  seed: 45
  tSimul: 100.0
  volume: 400
- !!python/object:cars.VehicleInput
  alignmentIdx: 1.0
  desiredSpeedParameters:
  - 14.0
  - 2.0
  headwayDistributionParameters: null
  seed: 90
  tSimul: 100.0
  volume: 400
vehicles: null
