!!python/object:objectsofworld.World
alignments:
- !!python/object:objectsofworld.Alignment
  connected_alignment_idx: 1
  controlDevice: null
  name: 'horizontal.yml'
  crossing_point: !!python/object:trafficintelligence.moving.Point
    x: 0.0
    y: 500.0
  distance_to_crossing_point: 1000.0
  volume: 700
  idx: 0
  points: !!python/object:trafficintelligence.moving.Trajectory
    cumulativeDistances:
    - 0.0
    - 1000.0
    - 1001.0
    - 2000.0
    distances:
    - 1000.0
    - 1.0
    - 999.0
    positions:
    - - -1000
      - 0.0
      - 1
      - 1000
    - - 500
      - 500.0
      - 500
      - 500
  width: null
- !!python/object:objectsofworld.Alignment
  connected_alignment_idx: 0
  controlDevice: null
  name: 'vertical.yml'
  crossing_point: !!python/object:trafficintelligence.moving.Point
    x: 0.0
    y: 500.0
  distance_to_crossing_point: 500.0
  volume: 500
  idx: 1
  points: !!python/object:trafficintelligence.moving.Trajectory
    cumulativeDistances:
    - 0.0
    - 500.0
    - 1000.0
    - 2000.0
    distances:
    - 500.0
    - 500.0
    - 1000.0
    positions:
    - - 0
      - 0.0
      - 0
      - 0
    - - 1000
      - 500.0
      - 0
      - -1000
  width: null
controlDevices: null
crossingPoint: !!python/object:trafficintelligence.moving.Point
  x: 0.0
  y: 500.0
pedestrians: null
vehicles: null
