!!python/object:objectsofworld.World
alignments:
- !!python/object:objectsofworld.Alignment
  connected_alignment_idx: 1
  controlDevice: null
  crossingPoint: !!python/object:trafficintelligence.moving.Point
    x: 500.0
    y: 500.0
  distance_to_crossing_point: 1500.0
  idx: 0
  points: !!python/object:trafficintelligence.moving.Trajectory
    cumulativeDistances:
    - 0.0
    - 1000.0
    - 1500.0
    - 1500.0
    - 1500.0
    - 2000.0
    distances:
    - 1000.0
    - 500.0
    - 0.0
    - 0.0
    - 500.0
    positions:
    - - -1000
      - 0
      - 500.0
      - 500.0
      - 500.0
      - 1000
    - - 500
      - 500
      - 500.0
      - 500.0
      - 500.0
      - 500
  width: null
- !!python/object:objectsofworld.Alignment
  connected_alignment_idx: 0
  controlDevice: null
  crossingPoint: !!python/object:trafficintelligence.moving.Point
    x: 500.0
    y: 500.0
  distance_to_crossing_point: 1500.0
  idx: 1
  points: !!python/object:trafficintelligence.moving.Trajectory
    cumulativeDistances:
    - 0.0
    - 1000.0
    - 1500.0
    - 1500.0
    - 1500.0
    - 2000.0
    distances:
    - 1000.0
    - 500.0
    - 0.0
    - 0.0
    - 500.0
    positions:
    - - 500
      - 500
      - 500.0
      - 500.0
      - 500.0
      - 500
    - - -1000
      - 0
      - 500.0
      - 500.0
      - 500.0
      - 1000
  width: null
controlDevices: null
crossingPoint: null
pedestrians: null
vehicleInputs:
- !!python/object:cars.VehicleInput
  aligmentIdx: 0
  fileName: horizontal.yml
  volume: 1000
- !!python/object:cars.VehicleInput
  aligmentIdx: 1
  fileName: vertical.yml
  volume: 700
vehicles: null
