!!python/object:simulation.Simulation
duration: 5
minNCompletedUsers: 10
timeStep: 0.1
safetyDistance: 1.0
verbose: False
seed: 44
increment: 4
rep: 1
dbName: pedestrians-data.db
computeInteractions: True
