!!python/object:simulation.Simulation
duration: 100
minNCompletedUsers: 5
timeStep: 0.1
safetyDistance: 1.0
verbose: False
seed: 44
increment: 4
rep: 2
dbName: stop-analysis.db
computeInteractions: True
